### ISSUE TITLE
Animación en slider

### ISSUE THREAD

**Issue by marcosbermejo** [pruzafa/immfly#1]
En móvil es necesario una animación en el cambio de slide al clicar en el botón Next/Previous. 

No es necesario efecto swipe (que al deslizar el dedo en móvil se cambie la slide) pero sí es necesaria una transición entre fotos que haga un movimiento de derecha a izquierda cuando pasa a la siguiente foto y de izquierda a derecha cuando pasa a la anterior.

Al llegar a la última no debe de continuar con la primera.
Al llegar a la primera no debe de continuar con la última

**Comment by pruzafa** [comment]
No se han usado animaciones CSS3 porque no todos los navegadores mobile las soportan. Se ha implementado una función _animate_ por Javascript.

**Comment by marcosbermejo** [comment]
ok! 

Una transition hubiera valido, porque los navegadores que sí las soportan son los navegadores con los que trabajamos (http://caniuse.com/#feat=css-transitions) pero por JS está muy bien también :+1:
